services:
  redis:
    build: ./docker/redis
    restart: unless-stopped
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"