services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      pg:
        condition: service_healthy
    container_name: kvault_api


  redis:
    build: ./docker/redis
    restart: unless-stopped
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    container_name: kvault_redis

  pg:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_DB: kvault
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: kvault_pg